Idego/Idego/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    url(r'^', include('companies.urls', namespace='companies')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^admin/', admin.site.urls),
]

Idego/companies/urls.py
from django.conf.urls import url

from .views import (
    IndexView,
    CompaniesListView,
    CompaniesCreateView,
    UsersListView,
    UsersDetailView,
    UsersCreateView,
    UsersEditView,
    UsersDeleteView,
)

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^companies/$', CompaniesListView.as_view(), name='companies'),
    url(r'^companies/create/$', CompaniesCreateView.as_view(), name='company-add'),
    url(r'^users/$', UsersListView.as_view(), name='users'),
    url(r'^users/create/$', UsersCreateView.as_view(), name='user-add'),
    url(r'^users/(?P<pk>[0-9]+)/$', UsersDetailView.as_view(), name='user-detail'),
    url(r'^users/edit/(?P<pk>[0-9]+)/$', UsersEditView.as_view(), name='user-edit'),
    url(r'^users/delete/(?P<pk>[0-9]+)/$', UsersDeleteView.as_view(), name='user-delete'),
]

Idego/companies/models.py
from django.db import models


# Create your models here.
class Company(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

Idego/companies/forms.py
from django import forms
from .models import Company
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, UserCreationForm


class CompanyCreateForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = [
            'name',
        ]


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User

        fields = [
            'username',
            'email',
            'first_name',
            'last_name'
        ]


class UserEditForm(UserChangeForm):
    class Meta:
        model = User

        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'user_permissions',
            'is_superuser',
            'is_staff',
            'is_active'
        ]

Idego/companies/views.py
from django.shortcuts import get_object_or_404

from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import CompanyCreateForm, UserEditForm, UserCreateForm
from .models import Company
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


# Create your views here.
class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'companies/index.html'


class CompaniesListView(LoginRequiredMixin, ListView):
    queryset = Company.objects.all()


class CompaniesCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    form_class = CompanyCreateForm
    template_name = 'companies/form.html'

    permission_required = 'companies.add_company'

    success_url = '/companies/'


class UsersListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return User.objects.all()


class UsersDetailView(LoginRequiredMixin, DetailView):
    model = User

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = get_object_or_404(User, pk=pk)
        return obj


class UsersCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    form_class = UserCreateForm
    template_name = 'companies/form.html'

    permission_required = 'auth.add_user'

    success_url = '/users/'


class UsersEditView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    form_class = UserEditForm
    template_name = 'companies/edit_form.html'

    permission_required = 'auth.change_user'

    success_url = '/users/'

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = get_object_or_404(User, pk=pk)
        return obj


class UsersDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = User
    success_url = '/users/'

    permission_required = 'auth.delete_user'

Idego/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Lists</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    {% load static %}
    <!--<link rel="stylesheet" href="{% static 'css/styles.css' %}">-->
</head>
<body>
{% include 'snippets/nav.html' %}
{% if messages %}
    <div class="alert messages text-center">
        {% for message in messages %}
        <b>{{ message }}</b><br/>
        {% endfor %}

    </div>
{% endif %}

    <div class='container'>
    {% block content %}{% endblock content %}
    </div>


</body>
</html>

Idego/templates/companies/company_list.html
{% extends "base.html" %}

{% block content %}

<h1>Companies</h1>
<a href='{% url "companies:company-add" %}' class="btn btn-primary">Add Company</a>
<ol>
{% for obj in object_list %}
    <li>{{ obj.name }}</li>
{% endfor %}
</ol>


{% endblock %}

Idego/templates/companies/edit_form.html
{% extends "base.html" %}

{% block content %}

<h1> Edit </h1>

<form method="POST"> {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-success">Submit</button>
</form>

{% endblock %}

Idego/templates/companies/form.html
{% extends "base.html" %}

{% block content %}

<h1> Add </h1>

<form method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

{% endblock %}

Idego/templates/companies/index.html
{% extends "base.html" %}

{% block content %}

<h1>Choose</h1>
<p>Welcome to <em>Lists</em>, a Django website.</p>

{% endblock %}

Idego/templates/snippets/nav.html
<div class='container'>
<div class='row text-center'>
<div clsas='col-sm-6 col-sm-offset-3'>
<h1>Lists</h1>
<a href='{% url "companies:index" %}' class="btn btn-primary">Home</a>
{% if request.user.is_authenticated %}
<a href='{% url "companies:companies" %}' class="btn btn-primary">Companies</a>
<a href='{% url "companies:users" %}' class="btn btn-primary">Users</a>
<a href='{% url "logout" %}' class="btn btn-danger">Logout</a>
{% endif %}
</div>
</div>

</div><hr/>